create extension if not exists pgcrypto;

drop table if exists public."success_rate" cascade;
drop table if exists public."teacher_subjects" cascade;
drop table if exists public."students" cascade;
drop table if exists public."teachers" cascade;
drop table if exists public."groups" cascade;
drop table if exists public."subjects" cascade;
drop table if exists public."control_types" cascade;
drop table if exists public."education_forms" cascade;
drop table if exists public."specializations" cascade;
drop table if exists public."departments" cascade;
drop table if exists public."profiles" cascade;

create table public."profiles" (
  "id" uuid primary key references auth.users(id) on delete cascade,
  "full_name" varchar(255) not null,
  "email" varchar(100) not null unique,
  "role" text not null check ("role" in ('admin', 'teacher', 'student')),
  "phone" varchar(20),
  "avatar_url" varchar(255),
  "created_at" timestamptz not null default now()
);

create table public."departments" (
  "DepartmentID" integer generated by default as identity primary key,
  "FullName" varchar(255) not null,
  "AbbreviatedName" varchar(50) not null
);

create table public."specializations" (
  "SpecID" integer generated by default as identity primary key,
  "SpecName" varchar(255) not null
);

create table public."education_forms" (
  "FormID" integer generated by default as identity primary key,
  "FormName" varchar(100) not null
);

create table public."groups" (
  "GroupID" integer generated by default as identity primary key,
  "SpecID" integer not null references public."specializations"("SpecID") on delete restrict,
  "StartYear" integer not null check ("StartYear" between 2000 and 2100),
  "ReleaseYear" integer not null check ("ReleaseYear" between 2000 and 2100),
  constraint "groups_years_check" check ("ReleaseYear" >= "StartYear")
);

create table public."students" (
  "StudentID" integer generated by default as identity primary key,
  "DepartmentID" integer not null references public."departments"("DepartmentID") on delete restrict,
  "GroupID" integer not null references public."groups"("GroupID") on delete restrict,
  "FormID" integer not null references public."education_forms"("FormID") on delete restrict,
  "profile_id" uuid references public."profiles"("id") on delete set null,
  "FullName" varchar(255) not null,
  "Birth_Date" date,
  "Email" varchar(100),
  "Phone" varchar(20)
);

create table public."teachers" (
  "TeacherID" integer generated by default as identity primary key,
  "DepartmentID" integer not null references public."departments"("DepartmentID") on delete restrict,
  "profile_id" uuid references public."profiles"("id") on delete set null,
  "FullName" varchar(255) not null,
  "Degree" varchar(100),
  "Birth_Date" date,
  "HireDate" date,
  "Email" varchar(100),
  "Phone" varchar(20)
);

create table public."subjects" (
  "SubjectID" integer generated by default as identity primary key,
  "SubjectName" varchar(255) not null
);

create table public."control_types" (
  "ControlTypeID" integer generated by default as identity primary key,
  "ControlTypeName" varchar(100) not null
);

create table public."teacher_subjects" (
  "TeacherSubjectID" integer generated by default as identity primary key,
  "TeacherID" integer not null references public."teachers"("TeacherID") on delete cascade,
  "SubjectID" integer not null references public."subjects"("SubjectID") on delete cascade,
  "CanEditGrades" boolean not null default true,
  constraint "teacher_subject_unique" unique ("TeacherID", "SubjectID")
);

create table public."success_rate" (
  "SuccRateID" integer generated by default as identity primary key,
  "TeacherID" integer not null references public."teachers"("TeacherID") on delete restrict,
  "StudentID" integer not null references public."students"("StudentID") on delete cascade,
  "SubjectID" integer not null references public."subjects"("SubjectID") on delete restrict,
  "ControlTypeID" integer not null references public."control_types"("ControlTypeID") on delete restrict,
  "AssessmentDate" date not null,
  "Mark" smallint not null check ("Mark" between 0 and 100),
  constraint "success_rate_unique" unique ("StudentID", "SubjectID", "ControlTypeID")
);

create or replace function public.current_role()
returns text
language sql
security definer
set search_path = public
as $$
  select "role" from public."profiles" where "id" = auth.uid()
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select public.current_role() = 'admin'
$$;

create or replace function public.current_teacher_id()
returns integer
language sql
security definer
set search_path = public
as $$
  select "TeacherID" from public."teachers" where "profile_id" = auth.uid()
$$;

create or replace function public.current_student_id()
returns integer
language sql
security definer
set search_path = public
as $$
  select "StudentID" from public."students" where "profile_id" = auth.uid()
$$;

alter table public."profiles" enable row level security;
alter table public."departments" enable row level security;
alter table public."specializations" enable row level security;
alter table public."education_forms" enable row level security;
alter table public."groups" enable row level security;
alter table public."students" enable row level security;
alter table public."teachers" enable row level security;
alter table public."subjects" enable row level security;
alter table public."control_types" enable row level security;
alter table public."teacher_subjects" enable row level security;
alter table public."success_rate" enable row level security;

create policy "public directories read" on public."departments" for select using (true);
create policy "public specializations read" on public."specializations" for select using (true);
create policy "public forms read" on public."education_forms" for select using (true);
create policy "public groups read" on public."groups" for select using (true);
create policy "public subjects read" on public."subjects" for select using (true);
create policy "public control types read" on public."control_types" for select using (true);

create policy "admin profiles all" on public."profiles" for all using (public.is_admin()) with check (public.is_admin());
create policy "own profile read" on public."profiles" for select using ("id" = auth.uid());
create policy "own profile update" on public."profiles" for update using ("id" = auth.uid()) with check ("id" = auth.uid());

create policy "admin departments all" on public."departments" for all using (public.is_admin()) with check (public.is_admin());
create policy "admin specializations all" on public."specializations" for all using (public.is_admin()) with check (public.is_admin());
create policy "admin forms all" on public."education_forms" for all using (public.is_admin()) with check (public.is_admin());
create policy "admin groups all" on public."groups" for all using (public.is_admin()) with check (public.is_admin());
create policy "admin subjects all" on public."subjects" for all using (public.is_admin()) with check (public.is_admin());
create policy "admin control all" on public."control_types" for all using (public.is_admin()) with check (public.is_admin());

create policy "students visible by role" on public."students"
for select using (
  public.is_admin()
  or public.current_role() = 'teacher'
  or "profile_id" = auth.uid()
);
create policy "admin students all" on public."students" for all using (public.is_admin()) with check (public.is_admin());

create policy "teachers visible by role" on public."teachers"
for select using (
  public.is_admin()
  or public.current_role() = 'student'
  or "profile_id" = auth.uid()
);
create policy "admin teachers all" on public."teachers" for all using (public.is_admin()) with check (public.is_admin());

create policy "teacher subjects visible" on public."teacher_subjects"
for select using (
  public.is_admin()
  or "TeacherID" = public.current_teacher_id()
);
create policy "admin teacher subjects all" on public."teacher_subjects" for all using (public.is_admin()) with check (public.is_admin());

create policy "success rate visible" on public."success_rate"
for select using (
  public.is_admin()
  or "TeacherID" = public.current_teacher_id()
  or "StudentID" = public.current_student_id()
);

create policy "admin success rate all" on public."success_rate"
for all using (public.is_admin()) with check (public.is_admin());

create policy "teacher success rate insert" on public."success_rate"
for insert with check (
  "TeacherID" = public.current_teacher_id()
  and exists (
    select 1 from public."teacher_subjects" ts
    where ts."TeacherID" = public.current_teacher_id()
      and ts."SubjectID" = "SubjectID"
      and ts."CanEditGrades" = true
  )
);

create policy "teacher success rate update" on public."success_rate"
for update using (
  "TeacherID" = public.current_teacher_id()
  and exists (
    select 1 from public."teacher_subjects" ts
    where ts."TeacherID" = public.current_teacher_id()
      and ts."SubjectID" = "SubjectID"
      and ts."CanEditGrades" = true
  )
) with check (
  "TeacherID" = public.current_teacher_id()
);
